---

- name: Create user
  user: name={{ user_name }} comment="Superhero"

- name: Copy public SSH key
  authorized_key: user={{ user_name }} key="{{ lookup('file', user_local_ssh_key_path) }}"

- name: Enable sudoers.d
  lineinfile: dest=/etc/sudoers state=present backup=yes regexp="^#includedir /etc/sudoers.d" line="#includedir /etc/sudoers.d"

- name: Enable passwordless sudo
  copy: content="%{{ user_name }} ALL=(ALL) NOPASSWD:ALL" dest=/etc/sudoers.d/{{ user_name }} owner=root group=root mode=0440
