---

- name: Create group(s)
  group:
    name: '{{ item }}'
  with_items: '{{ user_groups }}'
  when: user_groups | d()

- name: Create user
  user:
    generate_ssh_key: '{{ user_generate_ssh_key | d(omit) }}' 
    groups: '{{ (user_groups | join(",")) | d(omit) }}'
    append: True
    name: '{{ user_name }}'
    shell: '{{ user_shell | d(omit) }}'

- name: Set authorized_key to allow SSH based logins
  authorized_key:
    user: '{{ user_name }}'
    key: '{{ lookup("file", user_authorized_keys_path) }}'
  when: user_authorized_keys_path | d()

- name: Enable sudoers.d
  lineinfile:
    dest: '/etc/sudoers'
    state: 'present'
    backup: True
    regexp: '^#includedir /etc/sudoers.d'
    line: '#includedir /etc/sudoers.d'
  when: user_enable_passwordless_sudo | bool

- name: Enable passwordless sudo
  copy:
    content: '%{{ user_name }} ALL=(ALL) NOPASSWD:ALL'
    dest: '/etc/sudoers.d/{{ user_name }}'
    owner: 'root'
    group: 'root'
    mode: '0440'
  when: user_enable_passwordless_sudo | bool
